### ISSUE TITLE
Issue with how the output filepath is built

### ISSUE THREAD

**Issue by pawamoy** [laffra/pynsights#4]
```console
% python -m griffe griffe
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/media/data/dev/griffe/src/griffe/__main__.py", line 17, in <module>
    with pynsights.Recorder():
  File "/media/data/dev/griffe/__pypackages__/3.9/lib/pynsights/__init__.py", line 283, in __enter__
    start_tracing()
  File "/media/data/dev/griffe/__pypackages__/3.9/lib/pynsights/__init__.py", line 221, in start_tracing
    output = open(output_filename, "w")
FileNotFoundError: [Errno 2] No such file or directory: '/home/pawamoy/pynsights_trace_/usr/lib/python3.9/runpy.txt'
```

In that case pynsights probably got /usr/lib/python3.9/runpy as executable name/path. Could be fixed with `Path(execname).name` or something similar with `os.path` utils.

**Comment by laffra** [comment]
Have you tried passing a filename directly to `Recorder(filename)`?

**Comment by pawamoy** [comment]
I can work around the above issue by running my program differently: `pdm run griffe griffe`.
However, whatever the path I give (None, `griffe.txt`, `~/griffe.txt`), I get *nothing*. I can't find any txt file on my system with the output. No errors are shown though. I'll try to debug that.

**Comment by pawamoy** [comment]
It works when I run it in VSCode :thinking:

**Comment by pawamoy** [comment]
Ah, `pdm run` does not work because it calls the entrypoint function directly, not the `__main__` module where I put the Recorder context manager.

**Comment by pawamoy** [comment]
I got a fix, do you want a PR?

```python
if caller[1].endswith("runpy.py"):
    # prefer sys.argv[0]
    caller_module = sys.argv[0]
    if caller_module.endswith("__main__.py"):
        # use the directory name instead, which is the package name
        caller_module = os.path.dirname(caller_module)
else:
    caller_module = caller[1]

# keep only the base name without extension
caller_module = os.path.basename(caller_module.replace(".py", ""))

output_filename = "%s/pynsights_trace_%s.txt" % (os.path.expanduser('~'), caller_module)
```

**Comment by laffra** [comment]
OK. I never used `pdm`, so did not run into this issue 🤓.

**Comment by laffra** [comment]
Definitely. PR is great.
